# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-07 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190702_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(max_length=120, validators=[tweets.models.validate_content]),
        ),
    ]
